#define IDM_ABOUT      91
#define IDM_NREV       92
#define IDM_ZEBRA      93
#define IDM_DYNAMIC    94
#define IDM_STARTTORTURE 95
#define IDM_ENDTORTURE 96

#define IDD_ABOUT      81
#define IDD_NREV       82
#define IDD_NREV2      83
#define IDD_ZEBRA      84

#define ID_NREV_LEN    10
#define ID_NREV_CNT    11
#define ID_NREV2_LEN   12
#define ID_NREV2_CNT   13
#define ID_NREV2_TIME  14
#define ID_NREV2_LIPS  15

#define ID_ZHOUSE1     21
#define ID_ZHOUSE2     22
#define ID_ZHOUSE3     23
#define ID_ZHOUSE4     24
#define ID_ZHOUSE5     25
#define ID_ZTIME       26

#define ID_LISTBOX	30
#define ID_LBTEXT	31
#define ID_LBID 	32
#define ID_LBADD	33
#define ID_LBDELETE	34
#define ID_LBSAVE	35
#define ID_LBREVERSE	36
